### ISSUE TITLE
Not generating files with Flutter 3.10 / Dart 3?

### ISSUE THREAD

**Issue by biklas7** [petercinibulk/envied#28] opened 2023-05-10 22:25 UTC
After updating to the latest Flutter version it no longer generates the `env.g.dart` files.

Fails on both my machine with a local .env or on CI with environment variables.

**Comment by lcarrasco** [comment] 2023-05-11 01:24
Same over here

**Comment by meg4cyberc4t** [comment] 2023-05-11 06:49
Same issue

**Comment by seemihail1** [comment] 2023-05-11 06:57
faced same issue

**Comment by raghavsatyadev** [comment] 2023-05-11 07:35
I think dart version needs to be updated in packages

**Comment by FDuhen** [comment] 2023-05-11 07:54
Same here

**Comment by raghavsatyadev** [comment] 2023-05-11 09:20
Nope, it did not, I am deleting that pull request now.

**Comment by biklas7** [comment] 2023-05-11 09:27
Yeah tried something similar but it didn't work :(

Also tried to add to `build.yaml` something like:
```
      envied_generator:
        generate_for:
          include:
```
But it says `is not a known Builder`

**Comment by raghavsatyadev** [comment] 2023-05-11 09:29
The only solution I got was to copy that generated file for now in my system manually each time I run **build** command.

**Comment by biklas7** [comment] 2023-05-11 09:30
@petercinibulk sorry to tag you 🙏 Would it be possible to take a look into this?

**Comment by tusharbhambere** [comment] 2023-05-11 10:45
same issue

**Comment by mozerrr** [comment] 2023-05-11 10:54
Try to downgrade version of source_gen `source_gen: 1.3.0`

**Comment by reithealien** [comment] 2023-05-11 11:08
same issue

**Comment by mozerrr** [comment] 2023-05-11 11:35
> Try to downgrade version of source_gen
> 
> ```yaml
> dev_dependencies:
>   source_gen: 1.3.0
> ```

Actually it's this fix
```yaml
dev_dependencies:
  source_gen: 1.2.3
  build: 2.3.1
  build_runner: 2.3.0
  build_runner_core: 7.2.7
```
But i still have trouble with another package dependent on source_gen.

**Comment by mozerrr** [comment] 2023-05-11 12:06
> > Try to downgrade version of source_gen
> > ```yaml
> > dev_dependencies:
> >   source_gen: 1.3.0
> > ```
> 
> Upd. Not worked 😢 Something wrong with generators and transitive dependencies, because other packages based on source_gen have issues after release flutter 3.10 on public.

Finally found a source of problem. It was graphs, it was updated and broke build_runner.

To solve a problem do this:
```yaml
dev_dependencies:
  source_gen: 1.2.3
  graphs: 2.2.0
```

**Comment by techouse** [comment] 2023-05-11 12:09
> > > Try to downgrade version of source_gen
> > > ```yaml
> > > dev_dependencies:
> > >   source_gen: 1.3.0
> > > ```
> > 
> > 
> > Upd. Not worked 😢 Something wrong with generators and transitive dependencies, because other packages based on source_gen have issues after release flutter 3.10 on public.
> 
> Finally found a source of problem. It was graphs, it was updated and broke build_runner.
> 
> To solve a problem do this:
> 
> ```yaml
> dev_dependencies:
>   source_gen: 1.2.3
>   graphs: 2.2.0
> ```

Indeed it doesn't work with `graphs: 2.3.0`

**Comment by cmengler** [comment] 2023-05-11 12:16
Just posting this here if it is of any help -- I could see the `*.envied.g.dart` files generated successfully in the `.dart_tool/build/generated/*` directory, however, never to copied to `src`.

I haven't delved deep enough to understand these changes yet (late night already) -- however, my fix was to change the YAML syntax for `build_extensions` from:

```yaml
builders:
  envied:
    ...
    build_extensions:
      .dart:
        - envied.g.dart
```

to:

```yaml
builders:
  envied:
    ...
    build_extensions: { ".dart": [".envied.g.part"] }
```

**Comment by iyinusa** [comment] 2023-05-11 13:40
> ```yaml
> dependency_overrides:
>   envied_generator:
>     git:
>       url: https://github.com/cmengler/envied.git
>       path: packages/envied_generator
>       ref: fix-generator-build-extensions
> ```

Thanks, this works for now.

**Comment by petercinibulk** [comment] 2023-05-11 14:16
Big shout out to @cmengler for making a PR so quickly. I just published 0.3.1 with that fix.

I am going to reopen this issue for the near short term to track any other issues with Dart 3

**Comment by techouse** [comment] 2023-05-11 17:37
> I upgraded to 0.3.0+1. Now I get the following error.
> 
> Because envied_generator >=0.3.0+1 depends on analyzer ^5.12.0 and custom_lint_core
> 
> > =0.3.3 depends on analyzer >=5.7.0 <5.11.0, envied_generator >=0.3.0+1 is incompatible
> > with custom_lint_core >=0.3.3.
> > And because riverpod_generator >=2.2.0 depends on riverpod_analyzer_utils ^0.3.0 which
> > depends on custom_lint_core ^0.3.3, envied_generator >=0.3.0+1 is incompatible with
> > riverpod_generator >=2.2.0.

Dupe of https://github.com/petercinibulk/envied/issues/32

Fixed in https://github.com/petercinibulk/envied/pull/33

Just needs a new release.

**Comment by petercinibulk** [comment] 2023-05-11 17:39
@amin79 @techouse Just released 0.3.0+2

**Comment by amin79** [comment] 2023-05-11 17:50
@petercinibulk Thank you for your fast action :)
But still it does not create env.g.dart file. should I do something special?

**Comment by techouse** [comment] 2023-05-11 17:52
@amin79 have you tried force cleaning the generated files?

```bash
flutter pub run build_runner clean
flutter pub run build_runner build --delete-conflicting-outputs
```

**Comment by amin79** [comment] 2023-05-11 17:59
@techouse I have the following:
envied: ^0.3.0+2
envied_generator: ^0.3.0

Then I run:
````
flutter pub run build_runner clean
flutter pub run build_runner build --delete-conflicting-outputs
````

It does not create the file.

And with these versions:
envied: ^0.3.0+2
envied_generator: ^0.3.0+2

I get the following error:

Because envied_generator >=0.3.0+2 depends on analyzer ^5.11.1 and custom_lint_core 0.3.4 depends on analyzer >=5.7.0 <5.11.0, envied_generator >=0.3.0+2 is incompatible with custom_lint_core 0.3.4.
And because custom_lint_builder 0.3.4 depends on custom_lint_core 0.3.4, envied_generator >=0.3.0+2 is incompatible with custom_lint_builder 0.3.4.
Because custom_lint_builder >=0.3.3 <0.3.4 depends on custom_lint 0.3.3 and no versions of custom_lint_builder match >0.3.4 <0.4.0, custom_lint_builder >=0.3.3 <0.3.4-∞ or >0.3.4 <0.4.0 requires custom_lint 0.3.3.
Thus, if envied_generator >=0.3.0+2 and custom_lint_builder ^0.3.3 then custom_lint 0.3.3.
And because riverpod_lint 1.3.1 depends on custom_lint_builder ^0.3.3, if envied_generator >=0.3.0+2 and riverpod_lint 1.3.1 then custom_lint 0.3.3.

**Comment by amin79** [comment] 2023-05-11 18:24
@techouse Are they released or should I wait?

**Comment by abhinavdalal** [comment] 2023-05-12 04:52
using 0.3.0+3 for both envied and envied_generator has fixed issue for me.. really great to see quick response times from the community; specially @techouse and @petercinibulk!!

we really need an Root Cause Analysis(RCA) on why this happened in the first place.. and any actions we should take so that this doesnt happen in the future.. e.g. set compatible versions of dart/flutter in pubspec..

I will be happy to contribute some time if needed!

**Comment by amin79** [comment] 2023-05-12 06:25
I also confirm that it works now. Really thank you for your fast support :)

**Comment by iyinusa** [comment] 2023-05-12 07:33
I also confirmed the 0.3.0+3 for both envied and envied_generator works well.
Thanks, team.

**Comment by kaankoken** [comment] 2023-05-12 10:08
Our all packages have fixed version numbers & `version: 0.3.0` is broken somehow. Updating the envied to 0.3.0+3 broke other dependencies that we have.
<details>
  <summary>flutter doctor</summary>
    
    [✓] Flutter (Channel stable, 3.7.6, on macOS 13.3.1 22E772610a
      darwin-arm64, locale en-TR)
      • Flutter version 3.7.6 on channel stable at
        /Users/legolas/fvm/versions/3.7.6
      • Upstream repository
        https://github.com/flutter/flutter.git
      • Framework revision 12cb4eb7a0 (2 months ago), 2023-03-01
        10:29:26 -0800
      • Engine revision ada363ee93
      • Dart version 2.19.3
      • DevTools version 2.20.1

    [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
        • Android SDK at /Users/legolas/Library/Android/sdk
        • Platform android-33, build-tools 33.0.1
        • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
        • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 14.3)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Build 14E222b
        • CocoaPods version 1.12.0

    [✓] Chrome - develop for the web
        • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

    [✓] Android Studio (version 2022.1)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

    [✓] VS Code (version 1.78.2)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.64.0

    [✓] Connected device (3 available)
        • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
        • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
        • Chrome (web)                • chrome        • web-javascript • Google Chrome 113.0.5672.92

    [✓] HTTP Host Availability
        • All required HTTP hosts are available

    • No issues found!
</details>

<details>
  <summary>flutter dependencies</summary>
  
  ```bash
    Dart SDK 2.19.3
    Flutter SDK 3.7.6
    dependencies:
    - adjust_sdk 4.33.1 [flutter meta]
    - async 2.10.0 [collection meta]
    - audio_video_progress_bar 0.9.0 [flutter]
    - auto_orientation 2.2.1 [flutter]
    - auto_size_text 3.0.0 [flutter]
    - better_player 0.0.83 [flutter cupertino_icons wakelock meta flutter_widget_from_html_core visibility_detector path_provider collection xml]
    - cached_network_image 3.2.3 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
    - collection 1.17.0
    - connectivity_plus 3.0.3 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
    - cupertino_icons 1.0.5
    - dart_code_metrics 5.6.0 [analyzer analyzer_plugin ansicolor args collection crypto dart_code_metrics_presets file glob html meta path platform pub_updater source_span xml yaml]
    - device_info_plus 8.1.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32]
    - dio 5.1.1 [http_parser meta path]
    - dio_cache_interceptor 3.4.2 [dio uuid string_scanner]
    - envied 0.3.0
    - firebase_analytics 10.3.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
    - firebase_core 2.11.0 [firebase_core_platform_interface firebase_core_web flutter meta]
    - firebase_crashlytics 3.2.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
    - firebase_performance 0.9.1+2 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
    - firebase_remote_config 3.0.13 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
    - flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
    - flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
    - flutter_local_notifications 13.0.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
    - flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
    - flutter_pip 0.0.1 [flutter flutter_web_plugins plugin_platform_interface]
    - flutter_riverpod 2.3.6 [collection flutter meta riverpod state_notifier]
    - flutter_secure_storage 8.0.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
    - flutter_svg 2.0.2 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
    - flutter_video_cast 1.0.3 [flutter stream_transform]
    - freezed_annotation 2.2.0 [collection json_annotation meta]
    - google_fonts 4.0.3 [flutter http path_provider crypto]
    - hive 2.2.3 [meta crypto]
    - hive_flutter 1.1.0 [flutter hive path_provider path]
    - image_picker 0.8.6+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
    - in_app_purchase 3.0.6 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
    - intl 0.17.0 [clock path]
    - json_annotation 4.8.0 [meta]
    - mask_text_input_formatter 2.3.0 [flutter]
    - package_info_plus 3.0.3 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
    - path_provider 2.0.13 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
    - permission_handler 10.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
    - pretty_dio_logger 1.3.1 [dio]
    - retrofit 4.0.1 [dio meta]
    - share_plus 6.3.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
    - shimmer 2.0.0 [flutter]
    - smooth_page_indicator 1.0.1 [flutter]
    - store_redirect 2.0.1 [flutter]
    - subtitle_wrapper_package 2.1.0 [better_player bloc equatable flutter flutter_bloc http http_parser]
    - uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
    - url_launcher 6.1.10 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
    - version 3.0.2
    - video_player 2.2.5 [flutter meta video_player_platform_interface video_player_web html]
    - wakelock 0.6.1+2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
    - webview_flutter 4.0.5 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

    dev dependencies:
    - analyzer 5.4.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
    - build_runner 2.3.3 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
    - envied_generator 0.3.0 [envied build source_gen analyzer]
    - flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
    - freezed 2.3.2 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
    - hive_generator 2.0.0 [build source_gen hive analyzer source_helper]
    - json_serializable 6.6.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
    - retrofit_generator 6.0.0+1 [analyzer build built_collection code_builder dart_style dio retrofit source_gen tuple]

    transitive dependencies:
    - _fe_analyzer_shared 52.0.0 [meta]
    - _flutterfire_internals 1.2.0 [collection firebase_core firebase_core_platform_interface flutter meta]
    - analyzer_plugin 0.11.2 [analyzer collection dart_style pub_semver yaml]
    - ansicolor 2.0.1
    - args 2.4.1
    - bloc 8.1.1 [meta]
    - boolean_selector 2.1.1 [source_span string_scanner]
    - build 2.3.1 [analyzer async convert crypto glob logging meta path]
    - build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
    - build_daemon 3.1.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
    - build_resolvers 2.2.0 [analyzer async build collection crypto graphs logging path package_config pool pub_semver stream_transform yaml]
    - build_runner_core 7.2.7 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
    - built_collection 5.1.1
    - built_value 8.5.0 [built_collection collection fixnum meta]
    - cached_network_image_platform_interface 2.0.0 [flutter flutter_cache_manager]
    - cached_network_image_web 1.0.2 [flutter flutter_cache_manager cached_network_image_platform_interface]
    - characters 1.2.1
    - checked_yaml 2.0.3 [json_annotation source_span yaml]
    - clock 1.1.1
    - code_builder 4.4.0 [built_collection built_value collection matcher meta]
    - connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
    - convert 3.1.1 [typed_data]
    - cross_file 0.3.3+4 [js meta]
    - crypto 3.0.3 [typed_data]
    - csslib 0.17.2 [source_span]
    - dart_code_metrics_presets 1.7.0
    - dart_style 2.2.5 [analyzer args path pub_semver source_span]
    - dbus 0.7.8 [args ffi meta xml]
    - device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
    - equatable 2.0.5 [collection meta]
    - fake_async 1.3.1 [clock collection]
    - ffi 2.0.2
    - file 6.1.4 [meta path]
    - firebase_analytics_platform_interface 3.5.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
    - firebase_analytics_web 0.5.3 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
    - firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
    - firebase_core_web 2.5.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
    - firebase_crashlytics_platform_interface 3.5.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
    - firebase_performance_platform_interface 0.1.3 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
    - firebase_performance_web 0.1.3 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
    - firebase_remote_config_platform_interface 1.3.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
    - firebase_remote_config_web 1.3.0 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
    - fixnum 1.1.0
    - flutter_bloc 8.1.2 [flutter bloc provider]
    - flutter_blurhash 0.7.0 [flutter]
    - flutter_local_notifications_linux 3.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
    - flutter_local_notifications_platform_interface 6.0.0 [flutter plugin_platform_interface]
    - flutter_plugin_android_lifecycle 2.0.14 [flutter]
    - flutter_secure_storage_linux 1.1.3 [flutter flutter_secure_storage_platform_interface]
    - flutter_secure_storage_macos 3.0.0 [flutter flutter_secure_storage_platform_interface]
    - flutter_secure_storage_platform_interface 1.0.1 [flutter plugin_platform_interface]
    - flutter_secure_storage_web 1.1.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
    - flutter_secure_storage_windows 2.0.0 [flutter flutter_secure_storage_platform_interface]
    - flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
    - flutter_widget_from_html_core 0.8.5+3 [csslib flutter fwfh_text_style html]
    - frontend_server_client 3.2.0 [async path]
    - fwfh_text_style 2.22.08+1 [flutter]
    - glob 2.1.1 [async collection file path string_scanner]
    - graphs 2.3.0 [collection]
    - html 0.15.3 [csslib source_span]
    - http 0.13.6 [async http_parser meta]
    - http_multi_server 3.2.1 [async]
    - http_parser 4.0.2 [collection source_span string_scanner typed_data]
    - image_picker_android 0.8.6+13 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
    - image_picker_for_web 2.1.12 [flutter flutter_web_plugins image_picker_platform_interface]
    - image_picker_ios 0.8.7+4 [flutter image_picker_platform_interface]
    - image_picker_platform_interface 2.6.3 [cross_file flutter http plugin_platform_interface]
    - in_app_purchase_android 0.2.5+4 [collection flutter in_app_purchase_platform_interface json_annotation]
    - in_app_purchase_platform_interface 1.3.3 [flutter plugin_platform_interface]
    - in_app_purchase_storekit 0.3.6+3 [collection flutter in_app_purchase_platform_interface json_annotation]
    - io 1.0.4 [meta path string_scanner]
    - js 0.6.5 [meta]
    - logging 1.1.1
    - matcher 0.12.13 [meta stack_trace]
    - material_color_utilities 0.2.0
    - meta 1.8.0
    - mime 1.0.4
    - nested 1.0.0 [flutter]
    - nm 0.5.0 [dbus]
    - octo_image 1.0.2 [flutter flutter_blurhash]
    - package_config 2.1.0 [path]
    - package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
    - path 1.8.2
    - path_parsing 1.0.1 [vector_math meta]
    - path_provider_android 2.0.27 [flutter path_provider_platform_interface]
    - path_provider_foundation 2.2.3 [flutter path_provider_platform_interface]
    - path_provider_linux 2.1.10 [ffi flutter path path_provider_platform_interface xdg_directories]
    - path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
    - path_provider_windows 2.1.6 [ffi flutter path path_provider_platform_interface win32]
    - pedantic 1.11.1
    - permission_handler_android 10.2.0 [flutter permission_handler_platform_interface]
    - permission_handler_apple 9.0.8 [flutter permission_handler_platform_interface]
    - permission_handler_platform_interface 3.9.0 [flutter meta plugin_platform_interface]
    - permission_handler_windows 0.1.2 [flutter permission_handler_platform_interface]
    - petitparser 5.1.0 [meta]
    - platform 3.1.0
    - plugin_platform_interface 2.1.4 [meta]
    - pool 1.5.1 [async stack_trace]
    - process 4.2.4 [file path platform]
    - provider 6.0.5 [collection flutter nested]
    - pub_semver 2.1.4 [collection meta]
    - pub_updater 0.2.4 [http json_annotation process]
    - pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
    - riverpod 2.3.6 [meta stack_trace state_notifier]
    - rxdart 0.27.7
    - share_plus_platform_interface 3.2.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
    - shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
    - shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
    - sky_engine 0.0.99
    - source_gen 1.3.2 [analyzer async build dart_style glob path source_span yaml]
    - source_helper 1.3.3 [analyzer collection source_gen]
    - source_span 1.9.1 [collection path term_glyph]
    - sqflite 2.2.8+2 [flutter sqflite_common path]
    - sqflite_common 2.4.5 [synchronized path meta]
    - stack_trace 1.11.0 [path]
    - state_notifier 0.7.2+1 [meta]
    - stream_channel 2.1.1 [async]
    - stream_transform 2.1.0
    - string_scanner 1.2.0 [source_span]
    - synchronized 3.1.0
    - term_glyph 1.2.1
    - test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
    - timezone 0.9.2 [path]
    - timing 1.0.1 [json_annotation]
    - tuple 2.0.1
    - typed_data 1.3.2 [collection]
    - uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
    - uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
    - url_launcher_android 6.0.31 [flutter url_launcher_platform_interface]
    - url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
    - url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
    - url_launcher_macos 3.0.5 [flutter url_launcher_platform_interface]
    - url_launcher_platform_interface 2.1.2 [flutter plugin_platform_interface]
    - url_launcher_web 2.0.16 [flutter flutter_web_plugins url_launcher_platform_interface]
    - url_launcher_windows 3.0.6 [flutter url_launcher_platform_interface]
    - uuid 3.0.7 [crypto]
    - vector_graphics 1.1.5 [flutter vector_graphics_codec]
    - vector_graphics_codec 1.1.5
    - vector_graphics_compiler 1.1.5 [args meta path_parsing xml vector_graphics_codec]
    - vector_math 2.1.4
    - video_player_platform_interface 4.2.0 [flutter flutter_test meta]
    - video_player_web 2.0.15 [flutter flutter_web_plugins video_player_platform_interface]
    - visibility_detector 0.3.3 [flutter]
    - wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
    - wakelock_platform_interface 0.3.0 [flutter meta]
    - wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
    - wakelock_windows 0.2.1 [flutter wakelock_platform_interface win32]
    - watcher 1.0.2 [async path]
    - web_socket_channel 2.4.0 [async crypto stream_channel]
    - webview_flutter_android 3.7.0 [flutter webview_flutter_platform_interface]
    - webview_flutter_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
    - webview_flutter_wkwebview 3.4.3 [flutter path webview_flutter_platform_interface]
    - win32 3.1.4 [ffi]
    - xdg_directories 0.2.0+3 [meta path process]
    - xml 6.2.2 [collection meta petitparser]
    - yaml 3.1.2 [collection source_span string_scanner]
    ```

</details>

**Comment by quabynah-bilson** [comment] 2023-05-20 10:41
Hello guys 👋🏽. I have tried the proposed solutions but I still get the same error over and over again. Any assistance please?
<img width="1697" alt="image" src="https://github.com/petercinibulk/envied/assets/84394923/cc00a044-20af-4ab7-be81-d3342879d648">

**Comment by abhinavdalal** [comment] 2023-05-20 10:53
@quabynah-bilson  -> its +3 not -3 at the end of the version(as i see it in the screenshot)..

can you double check your issue is just related to incorrect version number in pubspec.yaml.. 
`envied: ^0.3.0+3`

https://pub.dev/packages/envied -> there is a copy button just to the right of version number in the heading.. thats what i use to avoid mistyping the version number..

**Comment by qcodelabsllc** [comment] 2023-05-20 10:54
Sorry. I updated it and did `flutter clean && flutter pub get`. I run the `dart run build_runner build` again and had the same issue

**Comment by techouse** [comment] 2023-05-20 10:57
@qcodelabsllc have you tried force cleaning the generated files?
 
```shell
flutter pub run build_runner clean
flutter pub run build_runner build --delete-conflicting-outputs
```

**Comment by quabynah-bilson** [comment] 2023-05-20 10:59
Yes please. I even did it again

**Comment by cmengler** [comment] 2023-05-20 11:01
> Hello guys 👋🏽. I have tried the proposed solutions but I still get the same error over and over again. Any assistance please?
> <img width="1697" alt="image" src="https://github.com/petercinibulk/envied/assets/84394923/cc00a044-20af-4ab7-be81-d3342879d648">
> 

The error message indicates it can't infer the type, have you tried `static final String key2 = ...`?

**Comment by quabynah-bilson** [comment] 2023-05-20 11:02
Thanks @cmengler . Works like magic 🎉
<img width="1728" alt="image" src="https://github.com/petercinibulk/envied/assets/84394923/1baaa632-b69c-45e0-be79-a2b5e607b4ef">

**Comment by quabynah-bilson** [comment] 2023-05-20 11:04
It works in my other projects too. Thanks again man. you've saved me a ton of explanation to do on Monday 😅

**Comment by cmengler** [comment] 2023-05-20 11:08
> It works in my other projects too. Thanks again man. you've saved me a ton of explanation to do on Monday 😅

Awesome! Happy to have help! 😀

**Comment by quabynah-bilson** [comment] 2023-05-30 13:05
> > Hello guys 👋🏽. I have tried the proposed solutions but I still get the same error over and over again. Any assistance please?
> > <img alt="image" width="1697" src="https://user-images.githubusercontent.com/84394923/239682719-cc00a044-20af-4ab7-be81-d3342879d648.png">
> 
> The error message indicates it can't infer the type, have you tried `static final String key2 = ...`?

@Terranic please refer to this response for your code issue

**Comment by LakshayDCoder** [comment] 2023-06-13 12:54
> ```shell
> flutter pub run build_runner build --delete-conflicting-outputs
> ```

@Terranic Did you manage to solve this issue? I am still getting the error & have been using all the latest libraries. Please do let me know if you were able to solve it.

**Comment by LakshayDCoder** [comment] 2023-06-13 12:54
> why I am getting this message when calling build_runner? (using 0.3.0+3 of envied)
> 
> ```
> [SEVERE] envied_generator:envied on lib/env/env.dart:
> 
> Environment variable not found for field `apiKey`.
> package:sg4/env/env.dart:8:23
>   ╷
> 8 │   static const String apiKey = _Env.apiKey;
>   │                       ^^^^^^
>   ╵
> [INFO] Running build completed, took 32.7s
> ```
> 
> source file:
> 
> ```
> import 'package:envied/envied.dart';
> 
> part 'env.g.dart';
> 
> @Envied(path: ".env")
> abstract class Env {
>   @EnviedField(varName: 'API_KEY')
>   static const String apiKey = _Env.apiKey;
> }
> ```
> 
> with the following .env file
> 
> `API_KEY=uUDpRX3c7NQrPr31599kFJVtSm1XS9eHySGvFA2aWn`

@Terranic Did you manage to solve this issue? I am still getting the error & have been using all the latest libraries. Please do let me know if you were able to solve it.

**Comment by quabynah-bilson** [comment] 2023-06-13 13:07
Yea please, he did. Kindly change the 'const' to 'final' and run the build runner again

**Comment by LakshayDCoder** [comment] 2023-06-13 13:12
> Yea please, he did. Kindly change the 'const' to 'final' and run the build runner again

I'm still getting the same error. Attaching the image below
![Screenshot 2023-06-13 184130](https://github.com/petercinibulk/envied/assets/32734770/bc42cfd1-1935-498d-bcce-d5944df90b29)

**Comment by quabynah-bilson** [comment] 2023-06-13 13:17
<img width="631" alt="image" src="https://github.com/petercinibulk/envied/assets/84394923/b099954e-6c56-4d1a-a366-a9f23154b841">


This is my implementation. Let's see if there are any differences aside the values themselves

**Comment by quabynah-bilson** [comment] 2023-06-13 13:18
What are your `build_runner` & `envied` + `envied_generator` versions?

**Comment by quabynah-bilson** [comment] 2023-06-13 13:20
dependencies:
envied: ^0.3.0+3

dev_dependencies:
 build_runner: ^2.4.5
 envied_generator: ^0.3.0+3

**Comment by quabynah-bilson** [comment] 2023-06-13 13:20
Perhaps, run `flutter pub upgrade --major-versions`. And then try to rebuild with the `build_runner`

**Comment by LakshayDCoder** [comment] 2023-06-13 13:38
> <img alt="image" width="631" src="https://user-images.githubusercontent.com/84394923/245487696-b099954e-6c56-4d1a-a366-a9f23154b841.png">
> This is my implementation. Let's see if there are any differences aside the values themselves

Ok, so I finally fixed it. I was mentioning the `path` argument in the `@Envied` annotation & the path was supposed to be from the root of the project. I fixed it by simply updating the path to `lib/env/.env`

**Comment by markbulingit** [comment] 2023-06-22 08:50
LATEST WORKING VERSION June 2023

1. Make sure the latest version of package(s) is installed

```
  dependencies:
      envied: ^0.3.0+3
   dev_dependencies:
       envied_generator: ^0.3.0+3
```

2. Make sure the Format of your .env (must be on root directory) is correct, (keys must have no "" )

`API_KEY="abc12345"`


3. On app/env/env.dart

```
@Envied()
abstract class Env {
  @EnviedField(varName: 'API_KEY')
  static final String apiKey = _Env.apiKey ;
}
```

**Comment by chillbrodev** [comment] 2023-07-28 19:39
> LATEST WORKING VERSION June 2023
> 
> 1. Make sure the latest version of package(s) is installed
> 
> ```
>   dependencies:
>       envied: ^0.3.0+3
>    dev_dependencies:
>        envied_generator: ^0.3.0+3
> ```
> 
>  2. Make sure the Format of your .env (must be on root directory) is correct, (keys must have no "" )
> 
> `API_KEY="abc12345"`
> 
> 3. On app/env/env.dart
> 
> ```
> @Envied()
> abstract class Env {
>   @EnviedField(varName: 'API_KEY')
>   static final String apiKey = _Env.apiKey ;
> }
> ```

Thank you! This saved my day

**Closed** 2023-08-26 08:52 UTC
Labels: question
