### ISSUE TITLE
Environment variable not found for field

### ISSUE THREAD

**Issue by rignaneseleo** [petercinibulk/envied#84] opened 2023-12-07 11:18 UTC
I'm using https://pub.dev/packages/dart_openai#api-key tutorial to set up my OpenAi key using envied.

### Setup

- **lib/env/.env**
`OPEN_AI_API_KEY=sk-cX....`

- **lib/env/env.dart**
```
// lib/env/env.dart
import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: ".env")
abstract class Env {
  @EnviedField(varName: 'OPEN_AI_API_KEY') // the .env variable.
  static final String apiKey = _Env.apiKey;
}
```

### Error

This is what I get when I run `flutter  pub run build_runner build --delete-conflicting-outputs`:

```
Environment variable not found for field `apiKey`.
package:parenthood/env/env.dart:9:23
  ╷
9 │   static final String apiKey = _Env.apiKey;
  │                       ^^^^^^
  ╵
```

I tried with:
- `flutter clean` before build_runner
- `dart run build_runner clean` before build_runner
- `dart run build_runner build` instead of pub run
- moving the `.env` file in the lib root
- using `static const apiKey` instead

Nothing worked.

### Environment

My `dev_dependencies`
```
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  # json_annotation: ^4.8.1
  freezed: ^2.4.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  envied_generator: ^0.5.2
```

**Comment by techouse** [comment] 2023-12-08 21:40
Possible duplicate of #6

**Comment by Giugiur** [comment] 2024-01-04 10:05
I'm experiencing the same on my end. No workaround is working for me and the path is okay.

**Comment by dIvYaNshhh** [comment] 2024-01-09 13:35
Same for me, any luck
i think the documentation is not proper, its kind of confusing to consume the library

**Comment by petercinibulk** [comment] 2024-01-11 14:20
@rignaneseleo @Giugiur I created a new dart project, installed the dependencies, and added the same files (lib/env/.env & lib/env/env.dart). To get it to run, you need to change the path of where the env file is located:
```dart
// lib/env/env.dart
import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: "lib/env/.env") // I CHANGED THIS LINE
abstract class Env {
  @EnviedField(varName: 'OPEN_AI_API_KEY') // the .env variable.
  static final String apiKey = _Env.apiKey;
}
```

It worked running running `dart run build_runner build --delete-conflicting-outputs`

Let me know if this works for you.

**Comment by petercinibulk** [comment] 2024-01-11 15:35
It will look for the file relative to the root of the project. I marked this issue for documentation to update the readme to make sure that it's clearer in the future

**Comment by Giugiur** [comment] 2024-01-11 16:29
Right, not relative to the location of the file itself but to the root.

**Comment by Artein** [comment] 2024-01-21 15:35
For me helped to manually delete generated files (`env_production.g.dart`) and to build once again. Seems like when you hit build again it won't rebuild existing files

**Comment by xmooncake** [comment] 2024-03-20 15:55
Glad you guys were able to solve it!

As mentioned in the first line of [Usage](https://github.com/petercinibulk/envied#usage) in the documentation:

"Add a .env file at the root of the project."

From my knowledge coming from laravel/node .env is always at the root of the project out of the box so i guess we could consider it a good practice, however it's just my perspective and could be wrong ;p

**Closed** 2024-03-21 14:25 UTC
Labels: documentation, question
