### ISSUE TITLE
Changes in .env file does not update generated env files

### ISSUE THREAD

**Issue by lordvidex** [petercinibulk/envied#6] opened 2022-08-20 22:47 UTC
## BEFORE
> .env
```env
SECRET=abc
```
> env.g.dart
```dart
class _Env {
  static const secret = 'abc';
}
```
## AFTER
> .env 
```env
SECRET=def
```
```bash
 $ flutter pub run build_runner build --delete-conflicting-outputs 
```

> env.g.dart 
```dart
class _Env {
  static const secret = 'abc';
}
```

**Comment by petercinibulk** [comment] 2022-08-21 01:02
Thanks for reporting this! I will need to do some digging into this one to see if there is any clever fix. This was still a problem with Envify, which this package is based on. For now the best piece of advice is to run ```flutter clean``` and then run the generator. I'm hoping there is a fix with the build or source_gen package to force a rebuild but I will have to do some searching.

**Comment by techouse** [comment] 2022-09-12 09:05
If this happens simply run

```shell
flutter pub run build_runner clean
```

which will clean all the generated files and purge the code-gen caches. Then run

```shell
flutter pub run build_runner build --delete-conflicting-outputs
```

as you normally would.

**Comment by isaacadariku** [comment] 2022-09-30 19:54
> If this happens simply run
> 
> ```shell
> flutter pub run build_runner clean
> ```
> 
> which will clean all the generated files and purge the code-gen caches. Then run
> 
> ```shell
> flutter pub run build_runner build --delete-conflicting-outputs
> ```
> 
> as you normally would.

Why this works, if you have a large project to run build runner and you have to keep clearing cache is not a good experience.

@petercinibulk please is any update coming on this sooner?

**Comment by diegog-sf** [comment] 2022-10-19 14:38
I think the issue is because it's not a dart file

**Comment by swiftymf** [comment] 2022-11-04 15:29
I'm having a similar issue. Running `flutter pub run build_runner clean` locally works, but I'm also using GH actions. I've added `flutter pub run build_runner clean` to run in the actions, but the new variable still isn't found. Not sure if someone has run into this and has a fix?

**Comment by petercinibulk** [comment] 2022-11-12 14:54
This is something that the build library does not currently support. I am tracking this issue: https://github.com/dart-lang/build/issues/967 If you know of a creative workaround you can make a pull request and I'd gladly review it! :)

**Comment by Meshkat-Shadik** [comment] 2023-05-10 20:48
I don't know why, when I first implement this, that was okay. After 2 days I run the command for generating other dto classes. But it's the same as this issue. I restarted my machine, flutter clean, cache clean everything I did. But the result is negative.

**Comment by Ali1Ammar** [comment] 2023-08-26 08:25
I also face the same issue with using export and system environment variables, the var is cached by the build_runner which does not get updated until the cache deleted?
is there any workaround for this? maybe building a separate generator without build_runner may fix this problem?

**Comment by Ali1Ammar** [comment] 2023-08-26 08:26
> I don't know why, when I first implement this, that was okay. After 2 days I run the command for generating other dto classes. But it's the same as this issue. I restarted my machine, flutter clean, cache clean everything I did. But the result is negative.

delete this folder `.dart_tool`

**Comment by Ali1Ammar** [comment] 2023-08-26 11:45
As a workaround we could delete the envied folder before running build 
`rm  .dart_tool/build/generated/nuqta/lib/env/env.envied.g.part && dart run build_runner build`
replace the path above with your path
We could also use [script_runner](https://pub.dev/packages/script_runner) to create a custom script for that command

```yaml
scripts:
  - generate:env: rm -r .dart_tool/build/generated/nuqta/lib/env && dart run build_runner build
```
and then we run `scr generate:env`

**Comment by mizukami2005** [comment] 2023-11-10 13:58
Maybe envied_generator has not been added!

The following command may solve the problem.

```shell
$ flutter pub add --dev envied_generator
＄flutter pub run build_runner build
```

**Comment by techouse** [comment] 2023-11-11 09:11
I'm closing this issue as the root cause https://github.com/dart-lang/build/issues/967 lies outside of this package and because a [workaround](https://github.com/petercinibulk/envied/issues/6#issuecomment-1243434607) has been provided.

**Closed by techouse** 2023-11-11 09:11 UTC
Labels: bug, enhancement, help wanted
