### ISSUE TITLE
env.g.dart not generated Flutter 3.19

### ISSUE THREAD

**Issue by jstdk** [petercinibulk/envied#90] opened 2024-02-18 07:19 UTC
I followed the exact steps as described here: https://pub.dev/packages/envied. Also followed some SO threads for the same issue in 2023. 

env.g.dart is not generated, whatever I try. The file is also not in the .dart_tools/build folder. 

Thanks for any suggestions.

**Comment by techouse** [comment] 2024-02-18 11:51
Hi,

I just tried re-generating one of my projects using Dart 3.3.0 (ships with Flutter 3.19.0) and it all works fine, so it seems to me as if you have an error in your setup. That being said, I did not try using it on a Flutter 3.19.0 project.

Can you confirm it works for you in Flutter 3.16.9?

Also, can you clone the example in this repo and try to rebuild it?

**Comment by techouse** [comment] 2024-02-24 13:23
Duplicate of https://github.com/petercinibulk/envied/issues/89

**Closed by techouse** 2024-02-24 13:23 UTC
Labels: question

**Comment by jstdk** [comment] 2024-02-24 15:41
Thanks @techouse, I followed the example and now it works. I had to move the files to the lib folder for it to work
