### ISSUE TITLE
Doesn't work in VM environments

### ISSUE THREAD

**Issue by BottlePumpkin** [petercinibulk/envied#37] opened 2023-05-25 09:30 UTC
I created an env file in a VM environment (e.g. codemagic) and tried to generate a .g file with the command flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs. 

`
Envied can only handle types such as `int`, `double`, `num`, `bool` and `String`. Type `InvalidType` is not one of them.
`

The error occurred continuously.

**Comment by RicharC293** [comment] 2023-05-29 16:31
Same error here

**Comment by RicharC293** [comment] 2023-05-29 17:24
@BottlePumpkin  solved here if you have same problem 
[dart analyzer](https://github.com/petercinibulk/envied/pull/38)

**Comment by techouse** [comment] 2023-08-26 08:50
Duplicate of https://github.com/petercinibulk/envied/issues/40

**Closed by techouse** 2023-08-26 08:50 UTC
