### ISSUE TITLE
"Environment variable not found for field" if build_runner hasn't been run without envied

### ISSUE THREAD

**Issue by jamesncl** [petercinibulk/envied#59] opened 2023-09-19 16:16 UTC
Whenever I create a fresh clone of my project, which uses envied, when I run `flutter pub run build_runner build --delete-conflicting-outputs` I always get:

> Environment variable not found for field `accessToken`.
package:my_project/env/env.dart:8:23
  ╷
8 │   static final String accessToken = _Env.accessToken;
  │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵

The only way I can resolve the problem is to comment out my env.dart file, run `build_runner` (which succeeds), then restore my env.dart and run `build_runner` again. Then the problem seems to fix itself. So basically, envied doesn't seem to work if you haven't run build_runner at least once without any envied code.

I'm using Flutter 3.13.1. My variables are stored in a file called `.env` at the root of my project.

Here's my env.dart:

```dart
import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied(path: '.env')
abstract class Env {
  @EnviedField(varName: 'ACCESS_TOKEN', obfuscate: true)
  static final String accessToken = _Env.accessToken;
}
```

And my `.env`:

```
ACCESS_TOKEN=my-token
```

**Comment by DarkHeros09** [comment] 2023-09-24 14:59
Any update on this issue? the package is not working right now.
```
[✓] Flutter (Channel stable, 3.13.4, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)
    • Flutter version 3.13.4 on channel stable at C:\Users\m_ben\.puro\envs\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (11 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

**Comment by atanasyordanov21** [comment] 2023-09-27 10:43
I have the same problem when adding new variables in my `.env` file. It always says that the new variable was not found. But as @jamesncl proposed, if I comment out the entire `env.dart` file (as if it doesn't exist at all), then run `build_runner`, then bring back `env.dart` (remove comments), then again `build_runner` - everything comes to its place. Anyway thanks for the great plugin!

**Comment by Saeeed-B** [comment] 2023-09-28 06:05
@atanasyordanov21 not this is not solution , and not workig.

**Comment by Saeeed-B** [comment] 2023-09-28 06:06
@petercinibulk please see this issue

**Comment by sonjz** [comment] 2023-10-25 15:36
The issue is build_runner cache related, there are 2 fixes:

- run `flutter clean` before running `build_runner` https://github.com/petercinibulk/envied/issues/6#issuecomment-1221439895

- or run `build_runner clean` before `build_runner build  --delete-conflicting-outputs` https://github.com/petercinibulk/envied/issues/6#issuecomment-1243434607

**Comment by techouse** [comment] 2023-10-26 20:49
Duplicate of #6

**Closed by techouse** 2023-10-26 20:49 UTC

**Comment by jamesncl** [comment] 2023-11-14 10:43
`build_runner clean` does appear to be a workaround, thanks. Should this be added to the envied README? Because as far as I can tell this package is essentially unusable without this crucial piece of knowledge. Alternatively, this issue and #6 should be left open until the root cause is fixed, so others can understand and find the workaround.

**Comment by techouse** [comment] 2023-11-14 22:01
> Should this be added to the envied README?

Good idea! Added in #77

**Comment by lionseye009** [comment] 2024-10-13 22:44
import 'dart:io';

main() {
  Directory current = Directory.current;

  print(current);
  print(current.path);
}

Run this to get your root path, it will be much longer.

I had to use this:
@Envied(path: '/home/username/Development/dart_test_project/bin/env/.env')

**Comment by rajeshjaluka** [comment] 2024-10-20 12:19
I tried the build clean and flutter clean, but I continue to get this error.

Here is my env.dart
```
import 'package:envied/envied.dart';

part 'env.g.dart';

// wasn't generating env.g.dart 
// ran - flutter pub add --dev envied_generator
@Envied(path: '.env', useConstantCase: true)
abstract class Env {
  @EnviedField(varName: 'BAAS_URL', obfuscate: true)
  static final String baasURL = _Env.baasURL;

  @EnviedField(varName: 'BAAS_KEY', obfuscate: true)
  static final String baasKey = _Env.baasKey;
}
```

the .env file has two entries with BAAS_URL and BAAS_KEY

The build keeps giving the following error 

[SEVERE] envied_generator:envied on lib/env/env.dart:

Environment variable not found for field `baasURL`.
package:flutter_demo/env/env.dart:10:23
   ╷
10 │   static final String baasURL = _Env.baasURL;
